version: '3'

services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    tmpfs: 
      - /usr/src/app/tmp
    command: 'bundle exec rails server -b 0.0.0.0'